environment:
  PATH:  C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%
  CASK_PYTHON: C:\Python27\python
  JUPYTER_PYTHON_VERSION: 3.6
  MINICONDA: C:\Miniconda3-x64
  EZMQ_VERSION: v0.10.1
  EZMQ_TZG: emacs-zmq-x86_64-w64-mingw32.tar.gz
matrix:
  fast_finish: true
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - pacman --needed --noconfirm -Syu
  - pacman --needed --noconfirm -Sy
  - pacman --needed --noconfirm -S mingw-w64-x86_64-emacs
  # Install Cask
  # NOTE: Using bash here so that cask writes to ~/.cask
  - bash -lc "curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | $CASK_PYTHON"
  - ps: |
      Add-Content -Path run-cask -Value @'
      #!/usr/bin/env bash
      $CASK_PYTHON ~/.cask/bin/cask $@
      '@
  - chmod +x run-cask
  - set PATH=%APPVEYOR_BUILD_FOLDER%;%PATH%
  - set CASK=run-cask
  # Install Jupyter
  - '"%MINICONDA%\Scripts\activate.bat"'
  - conda config --set always_yes yes --set changeps1 no
  - conda create --name jupyter python=%JUPYTER_PYTHON_VERSION%
  - conda activate jupyter
  - conda install jupyter
  # Ensure Jupyter runtime dir can be written to
  - ps: mkdir -p (jupyter --runtime-dir)
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - make dev
  # Download emacs-zmq dll binaries
  - ps: cd (Get-ChildItem -Recurse -Depth 2 -Path .cask -Filter zmq-*).FullName
  - appveyor DownloadFile https://github.com/dzop/emacs-zmq/releases/download/%EZMQ_VERSION%/%EZMQ_TZG%
  - tar -xzf %EZMQ_TZG%
  # NOTE: Set PATH to include the ZMQ directory so that emacs-zmq.dll can find
  # libzmq.dll and it needs to be at the front of PATH to ensure we find the
  # right one. See
  # https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order
  # TODO: Make this unnecessary
  - ps: $env:PATH = "$(Get-Location);$env:PATH"
test_script:
  - ps: |
      cd $env:APPVEYOR_BUILD_FOLDER
      make test
      Write-Host "Last Exit Code $LastExitCode"
      if ($LastExitCode -ne 0) {
          exit $LastExitCode
      }
